# Generated by Django 4.0.2 on 2023-11-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
